### ISSUE TITLE
package version does not update automatically without updating egg

### ISSUE THREAD

**Issue by bl-young** [USEPA/esupy#2]
Moving the conversation documented in this [pull request](https://github.com/USEPA/flowsa/pull/43#discussion_r574099999) to a new issue.

pkg_resources draws on the egg for the package version:
`pkg = pkg_resources.get_distribution("flowsa")`

For developers, when the version gets updated in setup.py, the egg-info on which pkg_resources draws does not automatically update.

Running the following within the package director will update the egg-info:
`python setup.py bdist_egg`
from: https://stackoverflow.com/a/3736104

**Comment by WesIngwersen** [comment]
This appears a duplicate of
