### ISSUE TITLE
Data Commons only returning first 1000 file names in `get_data_commons_index()`

### ISSUE THREAD

**Issue by bl-young** [USEPA/esupy#38]

**Comment by bl-young** [comment]
Flow by activity returns more than 1000 results:
```
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<Name>edap-ord-data-commons</Name>
<Prefix>flowsa/FlowByActivity/</Prefix>
<Marker/>
<MaxKeys>1000</MaxKeys>
<IsTruncated>true</IsTruncated>
```
Note IsTruncated: True

**Comment by bl-young** [comment]
@WesIngwersen I'm not sure if this is something that we will be able to work around given how we look for parquet files. cc @catherinebirney

**Comment by bl-young** [comment]
looks like we could use [boto3](https://pypi.org/project/boto3/), the AWS python package.

It looks like there is a way to access, filter, and read the object metadata from public repositories

**Comment by WesIngwersen** [comment]
We could archive older files right?

**Comment by bl-young** [comment]
Yes, at the risk of making old models unbuildable (perhaps less concerning for FBAs where the current issue is). We currently have 2267 files in flowsa/FlowByActivity.

I believe https://github.com/USEPA/esupy/commit/44e5420206c56d18c90bf600d7563eb239618d7f solves the issue but makes us dependent on a new package

**Comment by bl-young** [comment]
I created a new test (#39) to access and download a file from data commons (notably I picked USDA as its towards the end alphabetically). It's currently failing on main, but passes on #40
