### ISSUE TITLE
TypeError in context_secondary.py

### ISSUE THREAD

**Issue by dt-woods** [USEPA/esupy#56]
Have you run across this before? (Python 3.12; StEWI 1.1.3; esupy 0.3.3)
<img width="1180" alt="Screenshot 2024-12-04 at 12 04 06 PM" src="https://github.com/user-attachments/assets/48835161-3bdf-4f51-be30-55af67430daf">

**Comment by bl-young** [comment]
yes! just fixed it yesterday: https://github.com/USEPA/esupy/commit/b8617ffd38f7c1614fcbe28effdb71978ba503f1

**Comment by dt-woods** [comment]
Great! When's the patch release?

**Comment by bl-young** [comment]
Probably before the end of the week

**Comment by dt-woods** [comment]
Awesome. Thanks, Ben!

**Comment by dt-woods** [comment]
Solved in TRI, but the issue remains in NEI (see below).
<img width="1129" alt="image (5)" src="https://github.com/user-attachments/assets/3e59332c-4efa-4d8a-a319-5782d534e65b">

**Comment by dt-woods** [comment]
@bl-young , please reopen this issue.

**Comment by bl-young** [comment]
ah I had looked too quickly and had fixed in line 47 but not line 70. I will fix that.

> Kinda makes me not want to have geopandas installed when downloading stewi data.

Are you generating new stewi data besides what's already been published? Even in that case you shouldn't need to run it multiple times.

**Comment by bl-young** [comment]
ok @dt-woods you should be all set. I"ll leave this open until you can confirm

**Comment by dt-woods** [comment]
Cool. No, I'm working with a colleague who is setting up a downstream model that relies on ElectricityLCI and geopandas, which was how we ended up triggering this secondary context shenanigans. Didn't even know it existed!

**Comment by dt-woods** [comment]
FWIW: I'm probably not going to get to test this anytime soon; we implemented the work-around by uninstalling geopandas and running the 2020&ndash;2022 years to get copies of data without the secondary context info (skipped when geopandas is not found), and I'm not ready to clean out my data store and try again.

**Comment by bl-young** [comment]
all good - I expect this should do the trick.
